logging:
  level: INFO
  loggers:
    mchaitin: DEBUG

database:
  driverClass: org.postgresql.Driver
  user: docker
  password: docker
  url: jdbc:postgresql://db:5432/recipe_book
  properties:
    charSet: UTF-8
