version: "3.6"

services:
  db:
    build:
      context: ./Docker
      dockerfile: db.Dockerfile
    # volumes:
    #   - ./var/pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    image: postgres:13-alpine
  api:
    build:
      context: ./
      dockerfile: ./Docker/api.Dockerfile
    depends_on:
      - db
    ports:
      - "8080:8080"
      - "8081:8081"
    command: java -jar /data/ignant-nono-chortle-1.0-SNAPSHOT.jar server /data/config.yml
