version: "3.6"

services:
  db:
    build:
      context: ./Docker
      dockerfile: db.Dockerfile
    # volumes:
    #   - ./var/pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  # api:
  #   image: openjdk:13-alpine
  #   depends_on: ["db"]
